steps:
  - name: ':docker: :package:'
    agents:
      queue: builders
    plugins:
      'docker-compose#v1.7.0':
        build: fusion-tokens
        image-repository: 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber
  - wait
  - name: ':eslint:'
    command: yarn lint
    agents:
      queue: workers
    plugins:
      'docker-compose#v1.7.0':
        run: fusion-tokens
